// =============================================================
// FILE: src/i18n/staticUi.ts  (STATIK 10-DIL UI METINLERI)
// Phase 1: nav/blog/header/footer kodundaki `locale === 'tr' ? ... : ...` goc.
// Anahtar = Ingilizce metin. Uzun vade: DB site_settings ui_* ile birlesir.
// =============================================================

export const STATIC_UI: Record<string, Record<string, string>> = {
  'Everything About Preschool English Education': { 'tr': 'Okul Öncesi İngilizce Eğitimi Hakkında Her Şey', 'en': 'Everything About Preschool English Education', 'de': 'Alles über Englischunterricht im Vorschulalter', 'ar': 'كل ما يخص تعليم الإنجليزية في مرحلة ما قبل المدرسة', 'fr': 'Tout sur l\'enseignement de l\'anglais en maternelle', 'ru': 'Всё о дошкольном обучении английскому языку', 'es': 'Todo Sobre la Educación de Inglés Preescolar', 'it': 'Tutto sull\'insegnamento dell\'inglese alla scuola materna', 'nl': 'Alles over Engels onderwijs op de kleuterschool', 'pt-br': 'Tudo Sobre o Ensino de Inglês na Educação Infantil' },
  'Guides about preschool English education, play-based learning, Cambridge readiness and the Woody system.': { 'tr': 'Anaokulu İngilizce eğitimi, oyun temelli öğrenme, Cambridge hazırlık ve Woody sistemi hakkında kapsamlı rehberler.', 'en': 'Guides about preschool English education, play-based learning, Cambridge readiness and the Woody system.', 'de': 'Ratgeber zum Englischunterricht im Vorschulalter, spielbasiertem Lernen, Cambridge-Vorbereitung und dem Woody-System.', 'ar': 'أدلة حول تعليم الإنجليزية في مرحلة ما قبل المدرسة، والتعلم القائم على اللعب، والاستعداد لاختبارات Cambridge، ونظام Woody.', 'fr': 'Des guides sur l\'enseignement de l\'anglais en maternelle, l\'apprentissage par le jeu, la préparation Cambridge et le système Woody.', 'ru': 'Руководства по дошкольному обучению английскому, игровому обучению, подготовке к Cambridge и системе Woody.', 'es': 'Guías sobre educación de inglés preescolar, aprendizaje basado en el juego, preparación para Cambridge y el sistema Woody.', 'it': 'Guide sull\'insegnamento dell\'inglese alla scuola materna, l\'apprendimento basato sul gioco, la preparazione Cambridge e il sistema Woody.', 'nl': 'Gidsen over Engels onderwijs op de kleuterschool, spelend leren, Cambridge-voorbereiding en het Woody-systeem.', 'pt-br': 'Guias sobre ensino de inglês na educação infantil, aprendizagem baseada em brincadeiras, preparação para o Cambridge e o sistema Woody.' },
  'Complete Guide': { 'tr': 'Kapsamli Rehber', 'en': 'Complete Guide', 'de': 'Vollständiger Ratgeber', 'ar': 'الدليل الشامل', 'fr': 'Guide complet', 'ru': 'Полное руководство', 'es': 'Guía Completa', 'it': 'Guida completa', 'nl': 'Volledige gids', 'pt-br': 'Guia Completo' },
  'Complete Preschool English Education Guide': { 'tr': 'Anaokulu İngilizce Eğitimi Kapsamlı Rehber', 'en': 'Complete Preschool English Education Guide', 'de': 'Vollständiger Ratgeber zum Englischunterricht im Vorschulalter', 'ar': 'الدليل الشامل لتعليم الإنجليزية في مرحلة ما قبل المدرسة', 'fr': 'Guide complet de l\'enseignement de l\'anglais en maternelle', 'ru': 'Полное руководство по дошкольному обучению английскому языку', 'es': 'Guía Completa de Educación de Inglés Preescolar', 'it': 'Guida completa all\'inglese per la scuola materna', 'nl': 'Volledige gids voor Engels onderwijs op de kleuterschool', 'pt-br': 'Guia Completo de Ensino de Inglês na Educação Infantil' },
  'A long-form guide for building a preschool English system, planning teacher flow and presenting a trusted program to families.': { 'tr': 'Okul öncesi İngilizce sistemini kurmak, öğretmen akışını planlamak ve veliye güven veren bir program sunmak için uzun form rehber.', 'en': 'A long-form guide for building a preschool English system, planning teacher flow and presenting a trusted program to families.', 'de': 'Ein ausführlicher Ratgeber zum Aufbau eines Englischsystems für die Vorschule, zur Planung des Unterrichtsablaufs und zur Präsentation eines vertrauenswürdigen Programms für Familien.', 'ar': 'دليل مفصّل لبناء نظام إنجليزي لمرحلة ما قبل المدرسة، وتخطيط مسار المعلم، وتقديم برنامج موثوق للعائلات.', 'fr': 'Un guide détaillé pour bâtir un système d\'anglais en maternelle, planifier le déroulé de l\'enseignant et présenter aux familles un programme de confiance.', 'ru': 'Подробное руководство по созданию системы дошкольного английского, планированию работы преподавателя и представлению надёжной программы семьям.', 'es': 'Una guía extensa para construir un sistema de inglés preescolar, planificar el flujo del docente y presentar un programa confiable a las familias.', 'it': 'Una guida approfondita per costruire un sistema di inglese per la scuola materna, pianificare il flusso dell\'insegnante e presentare alle famiglie un programma affidabile.', 'nl': 'Een uitgebreide gids voor het opzetten van een Engels systeem voor de kleuterschool, het plannen van de lesopbouw en het presenteren van een betrouwbaar programma aan gezinnen.', 'pt-br': 'Um guia detalhado para construir um sistema de inglês na educação infantil, planejar o fluxo do professor e apresentar um programa confiável às famílias.' },
  'Read guide': { 'tr': 'Rehberi oku', 'en': 'Read guide', 'de': 'Ratgeber lesen', 'ar': 'اقرأ الدليل', 'fr': 'Lire le guide', 'ru': 'Читать руководство', 'es': 'Leer guía', 'it': 'Leggi la guida', 'nl': 'Lees de gids', 'pt-br': 'Ler guia' },
  'Articles': { 'tr': 'Yazilar', 'en': 'Articles', 'de': 'Artikel', 'ar': 'المقالات', 'fr': 'Articles', 'ru': 'Статьи', 'es': 'Artículos', 'it': 'Articoli', 'nl': 'Artikelen', 'pt-br': 'Artigos' },
  'Latest Blog Posts': { 'tr': 'Son Blog Yazıları', 'en': 'Latest Blog Posts', 'de': 'Neueste Blogbeiträge', 'ar': 'أحدث مقالات المدونة', 'fr': 'Derniers articles du blog', 'ru': 'Последние записи блога', 'es': 'Últimas Entradas del Blog', 'it': 'Ultimi articoli del blog', 'nl': 'Nieuwste blogberichten', 'pt-br': 'Últimas Publicações do Blog' },
  'Lesson planning, set selection, Cambridge readiness and play-based learning in one place.': { 'tr': 'Ders planı, set seçimi, Cambridge hazırlık ve oyun temelli öğrenme başlıkları tek yerde.', 'en': 'Lesson planning, set selection, Cambridge readiness and play-based learning in one place.', 'de': 'Unterrichtsplanung, Set-Auswahl, Cambridge-Vorbereitung und spielbasiertes Lernen an einem Ort.', 'ar': 'تخطيط الدروس واختيار المجموعات والاستعداد لاختبارات Cambridge والتعلم القائم على اللعب في مكان واحد.', 'fr': 'Plan de cours, choix des sets, préparation Cambridge et apprentissage par le jeu réunis en un seul endroit.', 'ru': 'Планирование уроков, выбор набора, подготовка к Cambridge и игровое обучение в одном месте.', 'es': 'Planificación de clases, selección de sets, preparación para Cambridge y aprendizaje basado en el juego en un solo lugar.', 'it': 'Pianificazione delle lezioni, scelta dei set, preparazione Cambridge e apprendimento basato sul gioco in un unico posto.', 'nl': 'Lesplanning, setselectie, Cambridge-voorbereiding en spelend leren op één plek.', 'pt-br': 'Planejamento de aulas, seleção de material, preparação para o Cambridge e aprendizagem baseada em brincadeiras em um só lugar.' },
  'Read more': { 'tr': 'Devamini oku', 'en': 'Read more', 'de': 'Weiterlesen', 'ar': 'اقرأ المزيد', 'fr': 'Lire la suite', 'ru': 'Читать далее', 'es': 'Leer más', 'it': 'Leggi di più', 'nl': 'Lees meer', 'pt-br': 'Leia mais' },
  'Frequently Asked About Woody': { 'tr': 'Woody Hakkında Sık Sorulanlar', 'en': 'Frequently Asked About Woody', 'de': 'Häufige Fragen zu Woody', 'ar': 'الأسئلة الشائعة حول Woody', 'fr': 'Questions fréquentes sur Woody', 'ru': 'Часто задаваемые вопросы о Woody', 'es': 'Preguntas Frecuentes Sobre Woody', 'it': 'Domande frequenti su Woody', 'nl': 'Veelgestelde vragen over Woody', 'pt-br': 'Perguntas Frequentes Sobre a Woody' },
  'Short answers to key blog questions, with problem, solution and classroom focus.': { 'tr': 'Blogdaki ana soruların kısa yanıtları: problem, çözüm ve uygulama odağıyla.', 'en': 'Short answers to key blog questions, with problem, solution and classroom focus.', 'de': 'Kurze Antworten auf zentrale Blogfragen, mit Fokus auf Problem, Lösung und Unterrichtspraxis.', 'ar': 'إجابات موجزة لأهم أسئلة المدونة، مع التركيز على المشكلة والحل والتطبيق الصفي.', 'fr': 'Des réponses courtes aux questions clés du blog, axées sur le problème, la solution et la classe.', 'ru': 'Краткие ответы на главные вопросы блога: проблема, решение и практический фокус.', 'es': 'Respuestas breves a las preguntas clave del blog, con enfoque en problema, solución y aula.', 'it': 'Risposte brevi alle domande chiave del blog, con focus su problema, soluzione e classe.', 'nl': 'Korte antwoorden op belangrijke blogvragen, met probleem, oplossing en focus op de klas.', 'pt-br': 'Respostas curtas às principais perguntas do blog, com foco em problema, solução e sala de aula.' },
  'Level finder': { 'tr': 'Seviye bulucu', 'en': 'Level finder', 'de': 'Niveaufinder', 'ar': 'محدّد المستوى', 'fr': 'Trouveur de niveau', 'ru': 'Определение уровня', 'es': 'Buscador de nivel', 'it': 'Trova il livello', 'nl': 'Niveauzoeker', 'pt-br': 'Localizador de nível' },
  'Problem: ': { 'tr': 'Sorun: ', 'en': 'Problem: ', 'de': 'Problem: ', 'ar': 'المشكلة: ', 'fr': 'Problème : ', 'ru': 'Проблема: ', 'es': 'Problema: ', 'it': 'Problema: ', 'nl': 'Probleem: ', 'pt-br': 'Problema: ' },
  'Solution: ': { 'tr': 'Çözüm: ', 'en': 'Solution: ', 'de': 'Lösung: ', 'ar': 'الحل: ', 'fr': 'Solution : ', 'ru': 'Решение: ', 'es': 'Solución: ', 'it': 'Soluzione: ', 'nl': 'Oplossing: ', 'pt-br': 'Solução: ' },
  'Latest Posts': { 'tr': 'Son Yazilar', 'en': 'Latest Posts', 'de': 'Neueste Beiträge', 'ar': 'أحدث المقالات', 'fr': 'Derniers articles', 'ru': 'Последние записи', 'es': 'Últimas Entradas', 'it': 'Ultimi articoli', 'nl': 'Nieuwste berichten', 'pt-br': 'Últimas Publicações' },
  'View All': { 'tr': 'Tumunu Gor', 'en': 'View All', 'de': 'Alle ansehen', 'ar': 'عرض الكل', 'fr': 'Voir tout', 'ru': 'Смотреть все', 'es': 'Ver Todo', 'it': 'Vedi tutti', 'nl': 'Alles bekijken', 'pt-br': 'Ver Todos' },
  'School': { 'tr': 'Okul', 'en': 'School', 'de': 'Schule', 'ar': 'المدرسة', 'fr': 'École', 'ru': 'Школа', 'es': 'Escuela', 'it': 'Scuola', 'nl': 'School', 'pt-br': 'Escola' },
  'Workshop': { 'tr': 'Atölye', 'en': 'Workshop', 'de': 'Workshop', 'ar': 'ورشة العمل', 'fr': 'Atelier', 'ru': 'Мастерская', 'es': 'Taller', 'it': 'Laboratorio', 'nl': 'Workshop', 'pt-br': 'Oficina' },
  'Home & Private Lesson': { 'tr': 'Ev & Özel Ders', 'en': 'Home & Private Lesson', 'de': 'Zuhause & Privatunterricht', 'ar': 'الدروس المنزلية والخصوصية', 'fr': 'Cours à domicile & particulier', 'ru': 'Домашние и частные уроки', 'es': 'Clase en Casa y Particular', 'it': 'Lezione a domicilio e privata', 'nl': 'Thuis & privéles', 'pt-br': 'Aula em Casa & Particular' },
  'Library': { 'tr': 'Kütüphane', 'en': 'Library', 'de': 'Bibliothek', 'ar': 'المكتبة', 'fr': 'Bibliothèque', 'ru': 'Библиотека', 'es': 'Biblioteca', 'it': 'Biblioteca', 'nl': 'Bibliotheek', 'pt-br': 'Biblioteca' },
  'Home': { 'tr': 'Ana sayfa', 'en': 'Home', 'de': 'Startseite', 'ar': 'الرئيسية', 'fr': 'Accueil', 'ru': 'Главная', 'es': 'Inicio', 'it': 'Home', 'nl': 'Home', 'pt-br': 'Início' },
  'A play-based and structured preschool English learning model.': { 'tr': 'Okul öncesi İngilizce eğitiminde oyun temelli ve sistemli öğrenme modeli.', 'en': 'A play-based and structured preschool English learning model.', 'de': 'Ein spielbasiertes und strukturiertes Englisch-Lernmodell für die Vorschule.', 'ar': 'نموذج تعليمي منظّم وقائم على اللعب للإنجليزية في مرحلة ما قبل المدرسة.', 'fr': 'Un modèle d\'apprentissage de l\'anglais en maternelle, ludique et structuré.', 'ru': 'Игровая и структурированная модель дошкольного обучения английскому языку.', 'es': 'Un modelo de aprendizaje de inglés preescolar basado en el juego y estructurado.', 'it': 'Un modello di apprendimento dell\'inglese per la scuola materna basato sul gioco e strutturato.', 'nl': 'Een spelend en gestructureerd Engels leermodel voor de kleuterschool.', 'pt-br': 'Um modelo de aprendizagem de inglês na educação infantil baseado em brincadeiras e estruturado.' },
  'Corporate': { 'tr': 'Kurumsal', 'en': 'Corporate', 'de': 'Unternehmen', 'ar': 'الشركات', 'fr': 'Entreprise', 'ru': 'Для организаций', 'es': 'Corporativo', 'it': 'Aziende', 'nl': 'Zakelijk', 'pt-br': 'Corporativo' },
  'Contact': { 'tr': 'İletişim', 'en': 'Contact', 'de': 'Kontakt', 'ar': 'اتصل بنا', 'fr': 'Contact', 'ru': 'Контакты', 'es': 'Contacto', 'it': 'Contatti', 'nl': 'Contact', 'pt-br': 'Contato' },
  'Contact us on WhatsApp': { 'tr': 'WhatsApp ile iletişime geçin', 'en': 'Contact us on WhatsApp', 'de': 'Kontaktieren Sie uns über WhatsApp', 'ar': 'تواصل معنا عبر WhatsApp', 'fr': 'Contactez-nous sur WhatsApp', 'ru': 'Напишите нам в WhatsApp', 'es': 'Contáctanos por WhatsApp', 'it': 'Contattaci su WhatsApp', 'nl': 'Neem contact met ons op via WhatsApp', 'pt-br': 'Fale conosco no WhatsApp' },
  'Follow Us': { 'tr': 'Bizi Takip Edin', 'en': 'Follow Us', 'de': 'Folgen Sie uns', 'ar': 'تابعنا', 'fr': 'Suivez-nous', 'ru': 'Подписывайтесь на нас', 'es': 'Síguenos', 'it': 'Seguici', 'nl': 'Volg ons', 'pt-br': 'Siga-nos' },
  'Woody Academy teacher application': { 'tr': 'Woody Academy öğretmen başvurusu', 'en': 'Woody Academy teacher application', 'de': 'Woody Academy Lehrerbewerbung', 'ar': 'طلب التحاق معلم Woody Academy', 'fr': 'Candidature enseignant Woody Academy', 'ru': 'Заявка преподавателя Woody Academy', 'es': 'Solicitud de docente de Woody Academy', 'it': 'Candidatura insegnante Woody Academy', 'nl': 'Woody Academy docentaanmelding', 'pt-br': 'Candidatura de professor da Woody Academy' },
  'Teacher Application': { 'tr': 'Öğretmen Başvurusu', 'en': 'Teacher Application', 'de': 'Lehrerbewerbung', 'ar': 'طلب التحاق معلم', 'fr': 'Candidature enseignant', 'ru': 'Заявка преподавателя', 'es': 'Solicitud de Docente', 'it': 'Candidatura insegnante', 'nl': 'Docentaanmelding', 'pt-br': 'Candidatura de Professor' },
  'ALL RIGHTS RESERVED.': { 'tr': 'TÜM HAKLARI SAKLIDIR.', 'en': 'ALL RIGHTS RESERVED.', 'de': 'ALLE RECHTE VORBEHALTEN.', 'ar': 'جميع الحقوق محفوظة.', 'fr': 'TOUS DROITS RÉSERVÉS.', 'ru': 'ВСЕ ПРАВА ЗАЩИЩЕНЫ.', 'es': 'TODOS LOS DERECHOS RESERVADOS.', 'it': 'TUTTI I DIRITTI RISERVATI.', 'nl': 'ALLE RECHTEN VOORBEHOUDEN.', 'pt-br': 'TODOS OS DIREITOS RESERVADOS.' },
  'Main navigation': { 'tr': 'Ana menü', 'en': 'Main navigation', 'de': 'Hauptnavigation', 'ar': 'القائمة الرئيسية', 'fr': 'Navigation principale', 'ru': 'Главное меню', 'es': 'Navegación principal', 'it': 'Navigazione principale', 'nl': 'Hoofdnavigatie', 'pt-br': 'Navegação principal' },
  'Language selection': { 'tr': 'Dil seçimi', 'en': 'Language selection', 'de': 'Sprachauswahl', 'ar': 'اختيار اللغة', 'fr': 'Choix de la langue', 'ru': 'Выбор языка', 'es': 'Selección de idioma', 'it': 'Selezione della lingua', 'nl': 'Taalkeuze', 'pt-br': 'Seleção de idioma' },
  'Language': { 'tr': 'Dil', 'en': 'Language', 'de': 'Sprache', 'ar': 'اللغة', 'fr': 'Langue', 'ru': 'Язык', 'es': 'Idioma', 'it': 'Lingua', 'nl': 'Taal', 'pt-br': 'Idioma' },
  'My profile': { 'tr': 'Profilim', 'en': 'My profile', 'de': 'Mein Profil', 'ar': 'ملفي الشخصي', 'fr': 'Mon profil', 'ru': 'Мой профиль', 'es': 'Mi perfil', 'it': 'Il mio profilo', 'nl': 'Mijn profiel', 'pt-br': 'Meu perfil' },
  'Profile': { 'tr': 'Profil', 'en': 'Profile', 'de': 'Profil', 'ar': 'الملف الشخصي', 'fr': 'Profil', 'ru': 'Профиль', 'es': 'Perfil', 'it': 'Profilo', 'nl': 'Profiel', 'pt-br': 'Perfil' },
  'Close mobile menu': { 'tr': 'Mobil menüyü kapat', 'en': 'Close mobile menu', 'de': 'Mobiles Menü schließen', 'ar': 'إغلاق قائمة الجوال', 'fr': 'Fermer le menu mobile', 'ru': 'Закрыть мобильное меню', 'es': 'Cerrar menú móvil', 'it': 'Chiudi il menu mobile', 'nl': 'Mobiel menu sluiten', 'pt-br': 'Fechar menu mobile' },
  'Open mobile menu': { 'tr': 'Mobil menüyü aç', 'en': 'Open mobile menu', 'de': 'Mobiles Menü öffnen', 'ar': 'فتح قائمة الجوال', 'fr': 'Ouvrir le menu mobile', 'ru': 'Открыть мобильное меню', 'es': 'Abrir menú móvil', 'it': 'Apri il menu mobile', 'nl': 'Mobiel menu openen', 'pt-br': 'Abrir menu mobile' },
  'Mobile menu': { 'tr': 'Mobil menü', 'en': 'Mobile menu', 'de': 'Mobiles Menü', 'ar': 'قائمة الجوال', 'fr': 'Menu mobile', 'ru': 'Мобильное меню', 'es': 'Menú móvil', 'it': 'Menu mobile', 'nl': 'Mobiel menu', 'pt-br': 'Menu mobile' },
  'All': { 'tr': 'Tümü', 'en': 'All', 'de': 'Alle', 'ar': 'الكل', 'fr': 'Tous', 'ru': 'Все', 'es': 'Todos', 'it': 'Tutti', 'nl': 'Alle', 'pt-br': 'Todos' },
  'Phone': { 'tr': 'Telefon', 'en': 'Phone', 'de': 'Telefon', 'ar': 'الهاتف', 'fr': 'Téléphone', 'ru': 'Телефон', 'es': 'Teléfono', 'it': 'Telefono', 'nl': 'Telefoon', 'pt-br': 'Telefone' },
  'Email': { 'tr': 'E-posta', 'en': 'Email', 'de': 'E-Mail', 'ar': 'البريد الإلكتروني', 'fr': 'E-mail', 'ru': 'Эл. почта', 'es': 'Correo electrónico', 'it': 'E-mail', 'nl': 'E-mail', 'pt-br': 'E-mail' },
  'Home Tutor': { 'tr': 'Ev Öğretmeni', 'en': 'Home Tutor', 'de': 'Privatlehrer', 'ar': 'معلم منزلي', 'fr': 'Professeur à domicile', 'ru': 'Домашний репетитор', 'es': 'Tutor a Domicilio', 'it': 'Insegnante a domicilio', 'nl': 'Privédocent aan huis', 'pt-br': 'Professor Particular' },
  'Woody Digital': { 'tr': 'Woody Dijital', 'en': 'Woody Digital', 'de': 'Woody Digital', 'ar': 'Woody الرقمي', 'fr': 'Woody Digital', 'ru': 'Woody Цифровой', 'es': 'Woody Digital', 'it': 'Woody Digital', 'nl': 'Woody Digital', 'pt-br': 'Woody Digital' },
  'Blog': { 'tr': 'Blog', 'en': 'Blog', 'de': 'Blog', 'ar': 'المدونة', 'fr': 'Blog', 'ru': 'Блог', 'es': 'Blog', 'it': 'Blog', 'nl': 'Blog', 'pt-br': 'Blog' },
  'Home Page': { 'tr': 'Ana Sayfa', 'en': 'Home Page', 'de': 'Startseite', 'ar': 'الصفحة الرئيسية', 'fr': 'Page d\'accueil', 'ru': 'Главная страница', 'es': 'Página de Inicio', 'it': 'Home', 'nl': 'Startpagina', 'pt-br': 'Página Inicial' },
  'Mobile navigation': { 'tr': 'Mobil menü', 'en': 'Mobile navigation', 'de': 'Mobile Navigation', 'ar': 'التنقل عبر الجوال', 'fr': 'Navigation mobile', 'ru': 'Мобильная навигация', 'es': 'Navegación móvil', 'it': 'Navigazione mobile', 'nl': 'Mobiele navigatie', 'pt-br': 'Navegação móvel' },
  'Menu': { 'tr': 'Menü', 'en': 'Menu', 'de': 'Menü', 'ar': 'القائمة', 'fr': 'Menu', 'ru': 'Меню', 'es': 'Menú', 'it': 'Menu', 'nl': 'Menu', 'pt-br': 'Menu' },
  'Sign out': { 'tr': 'Çıkış', 'en': 'Sign out', 'de': 'Abmelden', 'ar': 'تسجيل الخروج', 'fr': 'Se déconnecter', 'ru': 'Выйти', 'es': 'Cerrar sesión', 'it': 'Esci', 'nl': 'Uitloggen', 'pt-br': 'Sair' },
};

/** Statik UI metni — gecerli dildeki karsiligi (yoksa EN fallback). */
export function tUi(locale: string, en: string): string {
  const row = STATIC_UI[en];
  if (!row) return en;
  return row[locale] ?? row.en ?? en;
}
